name: Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  testing:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, 3.10]
        poetry-version: [1.0, 1.1.11]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Run Tests
        run: poetry run pytest --cov=src --cov-branch -v ./tests/* --cov-report=html
